### PR TITLE
Docker configuration

### PR DESCRIPTION
**Pull request by erogleva**
I have continued @ipa-nhg's work from #54 

- Regarding the visualizer, I think that the problem was just a typo/wrong port number. I have edited it now in the documentation and it worked fine for me. 

- I see two options to add the `index.yaml` file before running the container: 
    - either the `docker cp` command can be used (this, however, requires to create a new container, copy the file in it, commit the changes as a new image and run the new image (https://github.com/git-afsantos/haros/commit/451c5f63c6548d3d0637eafd7d8d15f00cc440cd), as far as I can see). 
    - the file can be added into the filesystem when running the image using a bind mount (https://github.com/git-afsantos/haros/commit/b69258b5608f5a05d89222a72ed5301f2b719cd0) with the --mount or -v options of the `docker run` command (the [docker documentation](https://docs.docker.com/storage/bind-mounts/) recommends the --mount syntax even though it is more verbose; I have listed both versions.
- Edit: I've also removed an instruction to copy the current directory contents into the container, I think this gets overwritten by the initialization of the workspace (and only the haros_call.sh file is needed)

### CODE REVIEW

**Comment by git-afsantos** [comment]
Thanks for the contribution, @erogleva!
If I understand correctly, this pull request completely replaces #54, right? Is it finished, or are you still working on something?

@erogleva wrote:
> I see two options to add the `index.yaml` file before running the container:

I agree with your assessment, and I see that you opted for mounting the file, which seems to be the most flexible option.

**Comment by erogleva** [comment]
> Is it finished, or are you still working on something?
I have added two more small changes (clang-3.8 as a dependency (I am not entirely sure if it is needed but I had some problems without it) and I've also added the `EXPOSE` instruction to the image to indicate which port is intended for publishing. But now it is finished :)

> If I understand correctly, this pull request completely replaces #54, right?
Yes, it was intended like that

**Comment by git-afsantos** [comment]
> clang-3.8 as a dependency (I am not entirely sure if it is needed but I had some problems without it)

What kind of problems, can you elaborate?
`clang` is just the frontend to the compiler, a standalone program that you can call on the terminal. `libclang` is what does the actual job for HAROS.

If the Docker container is intended to compile the workspace (e.g. `catkin_make`), then adding `clang` to the dependencies is a nice touch, though.

> But now it is finished :)

The PR seems good overall, so I am going to merge it and close the other one. :+1:

**Comment by erogleva** [comment]
> What kind of problems, can you elaborate?
clang is just the frontend to the compiler, a standalone program that you can call on the terminal. libclang is what does the actual job for HAROS.

> If the Docker container is intended to compile the workspace (e.g. catkin_make), then adding clang to the dependencies is a nice touch, though.

Ah yes, this was indeed the problem (only the compilation, nothing with HAROS). But yes, if I understand it correctly, the Docker container is also intended to compile the workspace (it currently also calls catkin_make in the `haros_call.sh`

**Comment by git-afsantos** [comment]
Alright, makes sense. :+1:

**Pull request merged**
